*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 11:48:01 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbiittest/tmp/MBIT.pid
open("/workspace/mbiittest/tmp/MBIT.pid"): No such file or directory [core/utils.c line 3624]
unlink(): No such file or directory [core/uwsgi.c line 1617]
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 11:49:15 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbiittest/tmp/MBIT.pid
open("/workspace/mbiittest/tmp/MBIT.pid"): No such file or directory [core/utils.c line 3624]
unlink(): No such file or directory [core/uwsgi.c line 1617]
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 11:51:06 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbiittest/tmp/MBIT.pid
open("/workspace/mbiittest/tmp/MBIT.pid"): No such file or directory [core/utils.c line 3624]
unlink(): No such file or directory [core/uwsgi.c line 1617]
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 12:35:02 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :80 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:40757 (port auto-assigned) fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x5641f4637450
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x5641f4637450 pid: 4487 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 4487)
spawned uWSGI worker 1 (pid: 4492, cores: 1)
spawned uWSGI http 1 (pid: 4493)
subprocess 4488 exited with code 0
[pid: 4492|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 2904 bytes} [Mon Jun 21 12:35:09 2021] GET / => generated 2528 bytes in 267 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Not Found: /static/css/reset.css
[pid: 4492|app: 0|req: 2/2] 172.17.0.1 () {52 vars in 2745 bytes} [Mon Jun 21 12:35:09 2021] GET /static/css/reset.css => generated 2460 bytes in 22 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /static/css/style.css
[pid: 4492|app: 0|req: 3/3] 172.17.0.1 () {52 vars in 2743 bytes} [Mon Jun 21 12:35:09 2021] GET /static/css/style.css => generated 2460 bytes in 36 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 4492|app: 0|req: 4/4] 172.17.0.1 () {58 vars in 2904 bytes} [Mon Jun 21 12:35:11 2021] GET / => generated 2528 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Not Found: /static/css/style.css
[pid: 4492|app: 0|req: 5/5] 172.17.0.1 () {52 vars in 2745 bytes} [Mon Jun 21 12:35:11 2021] GET /static/css/style.css => generated 2460 bytes in 124 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /static/css/reset.css
[pid: 4492|app: 0|req: 6/6] 172.17.0.1 () {52 vars in 2745 bytes} [Mon Jun 21 12:35:12 2021] GET /static/css/reset.css => generated 2460 bytes in 86 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 4492|app: 0|req: 7/7] 172.17.0.1 () {58 vars in 2903 bytes} [Mon Jun 21 12:35:46 2021] GET / => generated 2528 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Not Found: /static/css/style.css
[pid: 4492|app: 0|req: 8/8] 172.17.0.1 () {52 vars in 2745 bytes} [Mon Jun 21 12:35:47 2021] GET /static/css/style.css => generated 2460 bytes in 35 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
Not Found: /static/css/reset.css
[pid: 4492|app: 0|req: 9/9] 172.17.0.1 () {52 vars in 2745 bytes} [Mon Jun 21 12:35:47 2021] GET /static/css/reset.css => generated 2460 bytes in 29 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 4493)
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 12:35:58 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on :80 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43398 (port auto-assigned) fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x555d061f5450
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x555d061f5450 pid: 4532 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 4532)
spawned uWSGI worker 1 (pid: 4537, cores: 1)
spawned uWSGI http 1 (pid: 4538)
subprocess 4533 exited with code 0
[pid: 4537|app: 0|req: 1/1] 172.17.0.1 () {58 vars in 2904 bytes} [Mon Jun 21 12:36:01 2021] GET / => generated 2528 bytes in 262 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 4537|app: -1|req: -1/2] 172.17.0.1 () {52 vars in 2745 bytes} [Mon Jun 21 12:36:02 2021] GET /static/css/reset.css => generated 1092 bytes in 4 msecs via sendfile() (HTTP/1.1 200) 3 headers in 111 bytes (0 switches on core 0)
[pid: 4537|app: -1|req: -1/3] 172.17.0.1 () {52 vars in 2745 bytes} [Mon Jun 21 12:36:02 2021] GET /static/css/style.css => generated 3193 bytes in 1 msecs via sendfile() (HTTP/1.1 200) 3 headers in 111 bytes (0 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 4538)
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 12:43:38 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x564f6bf060e0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x564f6bf060e0 pid: 4891 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 4891)
spawned uWSGI worker 1 (pid: 4896, cores: 1)
subprocess 4892 exited with code 0
[pid: 4896|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2987 bytes} [Mon Jun 21 12:43:48 2021] GET / => generated 2528 bytes in 197 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 12:45:42 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x5575b30a3ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x5575b30a3ff0 pid: 5117 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 5117)
spawned uWSGI worker 1 (pid: 5122, cores: 1)
subprocess 5118 exited with code 0
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 0 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 12:45:48 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x5596a6347ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x5596a6347ff0 pid: 5140 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 5140)
spawned uWSGI worker 1 (pid: 5145, cores: 1)
subprocess 5141 exited with code 0
[pid: 5145|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2941 bytes} [Mon Jun 21 12:45:53 2021] GET / => generated 2528 bytes in 193 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 12:56:34 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x556b8e05cff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 4 seconds on interpreter 0x556b8e05cff0 pid: 5759 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 5759)
spawned uWSGI worker 1 (pid: 5763, cores: 1)
subprocess 5760 exited with code 0
[pid: 5763|app: 0|req: 1/1] 172.17.0.1 () {62 vars in 2972 bytes} [Mon Jun 21 12:56:38 2021] GET / => generated 2528 bytes in 378 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 5763|app: 0|req: 2/2] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 12:57:25 2021] GET /result/1 => generated 5347 bytes in 13 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 13:03:45 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x55e784fd2ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55e784fd2ff0 pid: 5867 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 5867)
spawned uWSGI worker 1 (pid: 5870, cores: 1)
subprocess 5868 exited with code 0
[pid: 5870|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 13:03:48 2021] GET /result/1 => generated 5347 bytes in 296 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 5870|app: 0|req: 2/2] 172.17.0.1 () {60 vars in 2962 bytes} [Mon Jun 21 13:03:51 2021] GET / => generated 2528 bytes in 80 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 5870|app: 0|req: 3/3] 172.17.0.1 () {60 vars in 2964 bytes} [Mon Jun 21 13:03:56 2021] GET /form/ => generated 38246 bytes in 423 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 13:07:13 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x55ea2b0feff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x55ea2b0feff0 pid: 5911 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 5911)
spawned uWSGI worker 1 (pid: 5914, cores: 1)
subprocess 5912 exited with code 0
[pid: 5914|app: 0|req: 1/1] 172.17.0.1 () {62 vars in 2995 bytes} [Mon Jun 21 13:07:17 2021] GET /form/ => generated 38246 bytes in 1147 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 5914|app: 0|req: 2/2] 172.17.0.1 () {68 vars in 3171 bytes} [Mon Jun 21 13:07:39 2021] POST /submit/ => generated 0 bytes in 165 msecs (HTTP/1.1 302) 6 headers in 188 bytes (1 switches on core 0)
[pid: 5914|app: 0|req: 3/3] 172.17.0.1 () {62 vars in 3006 bytes} [Mon Jun 21 13:07:42 2021] GET /result/5 => generated 5261 bytes in 11 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 5914|app: 0|req: 4/4] 172.17.0.1 () {62 vars in 3006 bytes} [Mon Jun 21 13:07:55 2021] GET /result/5 => generated 5261 bytes in 83 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 5914|app: 0|req: 5/5] 172.17.0.1 () {62 vars in 3006 bytes} [Mon Jun 21 13:08:00 2021] GET /result/5 => generated 5261 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 5914|app: 0|req: 6/6] 172.17.0.1 () {62 vars in 3006 bytes} [Mon Jun 21 13:08:06 2021] GET /result/5 => generated 5261 bytes in 79 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 13:16:17 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x5619c9265ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x5619c9265ff0 pid: 5937 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 5937)
spawned uWSGI worker 1 (pid: 5940, cores: 1)
subprocess 5938 exited with code 0
[pid: 5940|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2962 bytes} [Mon Jun 21 13:16:22 2021] GET / => generated 2558 bytes in 345 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 13:22:20 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x55e9ba527ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55e9ba527ff0 pid: 5959 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 5959)
spawned uWSGI worker 1 (pid: 5962, cores: 1)
subprocess 5960 exited with code 0
[pid: 5962|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2987 bytes} [Mon Jun 21 13:22:24 2021] GET / => generated 2510 bytes in 171 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 5962|app: 0|req: 2/2] 172.17.0.1 () {60 vars in 3010 bytes} [Mon Jun 21 13:22:25 2021] GET /form/ => generated 38279 bytes in 226 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 5962|app: 0|req: 3/3] 172.17.0.1 () {68 vars in 3171 bytes} [Mon Jun 21 13:22:48 2021] POST /submit/ => generated 0 bytes in 81 msecs (HTTP/1.1 302) 6 headers in 188 bytes (1 switches on core 0)
[pid: 5962|app: 0|req: 4/4] 172.17.0.1 () {62 vars in 3006 bytes} [Mon Jun 21 13:22:48 2021] GET /result/4 => generated 5140 bytes in 12 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 14:10:34 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x56198abe3ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x56198abe3ff0 pid: 7341 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 7341)
spawned uWSGI worker 1 (pid: 7346, cores: 1)
subprocess 7342 exited with code 0
[pid: 7346|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2941 bytes} [Mon Jun 21 14:10:37 2021] GET / => generated 2473 bytes in 319 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 7346|app: 0|req: 2/2] 172.17.0.1 () {60 vars in 2964 bytes} [Mon Jun 21 14:10:41 2021] GET /form/ => generated 37977 bytes in 397 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
Gracefully killing worker 1 (pid: 7346)...
...gracefully killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /workspace/mbittest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/workspace/mbittest/tmp/MBIT.sock)
running /workspace/mbittest/venv/bin/uwsgi
[uWSGI] getting INI configuration from /workspace/mbittest/.config/uwsgi/uwsgi.ini
[uwsgi-static] added mapping for /static => /workspace/mbittest/staticfiles/
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 14:44:39 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x5621031f7f80
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 3 seconds on interpreter 0x5621031f7f80 pid: 7341 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 7341)
spawned uWSGI worker 1 (pid: 9052, cores: 1)
subprocess 8893 exited with code 0
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 15:28:12 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x55d246bf1ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x55d246bf1ff0 pid: 455 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 455)
spawned uWSGI worker 1 (pid: 459, cores: 1)
subprocess 456 exited with code 0
[pid: 459|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2987 bytes} [Mon Jun 21 15:28:19 2021] GET / => generated 2473 bytes in 196 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 2/2] 172.17.0.1 () {60 vars in 2964 bytes} [Mon Jun 21 15:28:53 2021] GET /form/ => generated 37977 bytes in 428 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 3/3] 172.17.0.1 () {60 vars in 2929 bytes} [Mon Jun 21 15:30:14 2021] GET /form/ => generated 37977 bytes in 527 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 4/4] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 15:30:18 2021] GET /result/1 => generated 7411 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 5/5] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:34:13 2021] GET /result/1 => generated 7411 bytes in 83 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 6/6] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:34:57 2021] GET /result/1 => generated 7411 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 7/7] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:34:59 2021] GET /result/1 => generated 7411 bytes in 84 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 8/8] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:39:33 2021] GET /result/1 => generated 7411 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 9/9] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:39:34 2021] GET /result/1 => generated 7411 bytes in 104 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 10/10] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:42:30 2021] GET /result/1 => generated 7411 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 11/11] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:43:13 2021] GET /result/1 => generated 7453 bytes in 74 msecs (HTTP/1.1 200) 5 headers in 167 bytes (2 switches on core 0)
[pid: 459|app: 0|req: 12/12] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:45:10 2021] GET /result/1 => generated 7485 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 13/13] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:46:48 2021] GET /result/1 => generated 7485 bytes in 72 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 14/14] 172.17.0.1 () {60 vars in 2962 bytes} [Mon Jun 21 15:47:09 2021] GET / => generated 2473 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 15/15] 172.17.0.1 () {60 vars in 2964 bytes} [Mon Jun 21 15:47:15 2021] GET /form/ => generated 37977 bytes in 456 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 16/16] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 15:47:26 2021] GET /result/1 => generated 7485 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 17/17] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 15:47:29 2021] GET /result/2 => generated 7492 bytes in 18 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 459|app: 0|req: 18/18] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 15:47:32 2021] GET /result/3 => generated 7458 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 15:48:44 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x55ab771a0ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 2 seconds on interpreter 0x55ab771a0ff0 pid: 1807 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 1807)
spawned uWSGI worker 1 (pid: 1812, cores: 1)
subprocess 1808 exited with code 0
[pid: 1812|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2987 bytes} [Mon Jun 21 15:48:46 2021] GET / => generated 2473 bytes in 124 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1812|app: 0|req: 2/2] 172.17.0.1 () {60 vars in 3010 bytes} [Mon Jun 21 15:48:49 2021] GET /form/ => generated 37977 bytes in 448 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 1812|app: 0|req: 3/3] 172.17.0.1 () {58 vars in 2957 bytes} [Mon Jun 21 15:48:56 2021] GET /result/2 => generated 7492 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1812|app: 0|req: 4/4] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:49:22 2021] GET /result/2 => generated 7492 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1812|app: 0|req: 5/5] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 15:49:29 2021] GET /result/1 => generated 7485 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1812|app: 0|req: 6/6] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:51:10 2021] GET /result/1 => generated 7483 bytes in 12 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1812|app: 0|req: 7/7] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 15:51:14 2021] GET /result/2 => generated 7490 bytes in 96 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1812|app: 0|req: 8/8] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 15:51:18 2021] GET /result/3 => generated 7456 bytes in 12 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 1812|app: 0|req: 9/9] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 15:52:01 2021] GET /result/3 => generated 7550 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
SIGINT/SIGQUIT received...killing workers...
worker 1 buried after 1 seconds
goodbye to uWSGI.
VACUUM: pidfile removed.
VACUUM: unix socket /workspace/mbittest/tmp/MBIT.sock removed.
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 15:57:26 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
writing pidfile to /workspace/mbittest/tmp/MBIT.pid
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x561232621ff0
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x561232621ff0 pid: 2302 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
spawned uWSGI master process (pid: 2302)
spawned uWSGI worker 1 (pid: 2306, cores: 1)
subprocess 2303 exited with code 0
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./MBIT/urls.py", line 7, in <module>
    path('', include('main.urls')),
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 1
    from django.urls import path
    ^
IndentationError: unexpected indent
[pid: 2306|app: 0|req: 1/1] 172.17.0.1 () {60 vars in 2962 bytes} [Mon Jun 21 15:57:36 2021] GET / => generated 141738 bytes in 435 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./MBIT/urls.py", line 7, in <module>
    path('', include('main.urls')),
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 1
    from django.urls import path
    ^
IndentationError: unexpected indent
[pid: 2306|app: 0|req: 2/2] 172.17.0.1 () {60 vars in 2962 bytes} [Mon Jun 21 15:58:10 2021] GET / => generated 141738 bytes in 234 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./MBIT/urls.py", line 7, in <module>
    path('', include('main.urls')),
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 1
    from django.urls import path
    ^
IndentationError: unexpected indent
[pid: 2306|app: 0|req: 3/3] 172.17.0.1 () {60 vars in 2962 bytes} [Mon Jun 21 15:58:15 2021] GET / => generated 141738 bytes in 427 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./MBIT/urls.py", line 7, in <module>
    path('', include('main.urls')),
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 1
    from django.urls import path
    ^
IndentationError: unexpected indent
[pid: 2306|app: 0|req: 4/4] 172.17.0.1 () {60 vars in 2926 bytes} [Mon Jun 21 15:58:20 2021] GET / => generated 141702 bytes in 247 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./MBIT/urls.py", line 7, in <module>
    path('', include('main.urls')),
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 1
    from django.urls import path
    ^
IndentationError: unexpected indent
[pid: 2306|app: 0|req: 5/5] 172.17.0.1 () {60 vars in 2926 bytes} [Mon Jun 21 15:58:31 2021] GET / => generated 141702 bytes in 436 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./MBIT/urls.py", line 7, in <module>
    path('', include('main.urls')),
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 1
    from django.urls import path
    ^
IndentationError: unexpected indent
[pid: 2306|app: 0|req: 6/6] 172.17.0.1 () {60 vars in 2941 bytes} [Mon Jun 21 15:58:37 2021] GET / => generated 141717 bytes in 387 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
Internal Server Error: /
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 167, in _get_response
    callback, callback_args, callback_kwargs = self.resolve_request(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 290, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 556, in resolve
    for pattern in self.url_patterns:
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./MBIT/urls.py", line 7, in <module>
    path('', include('main.urls')),
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main/urls.py", line 1
    from django.urls import path
    ^
IndentationError: unexpected indent
[pid: 2306|app: 0|req: 7/7] 172.17.0.1 () {60 vars in 2941 bytes} [Mon Jun 21 15:59:29 2021] GET / => generated 141717 bytes in 377 msecs (HTTP/1.1 500) 6 headers in 187 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 8/8] 172.17.0.1 () {62 vars in 2972 bytes} [Mon Jun 21 15:59:46 2021] GET / => generated 2473 bytes in 45 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 9/9] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 15:59:52 2021] GET /result/1 => generated 7568 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 10/10] 172.17.0.1 () {60 vars in 2949 bytes} [Mon Jun 21 16:00:32 2021] GET /result/1 => generated 7579 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 11/11] 172.17.0.1 () {60 vars in 2984 bytes} [Mon Jun 21 16:00:33 2021] GET /all_results => generated 1546 bytes in 5 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 12/12] 172.17.0.1 () {60 vars in 2981 bytes} [Mon Jun 21 16:00:35 2021] GET /result/2 => generated 7586 bytes in 14 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 13/13] 172.17.0.1 () {62 vars in 3012 bytes} [Mon Jun 21 16:03:14 2021] GET /result/2 => generated 7586 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 14/14] 172.17.0.1 () {62 vars in 3012 bytes} [Mon Jun 21 16:05:20 2021] GET /result/2 => generated 7586 bytes in 80 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 15/15] 172.17.0.1 () {62 vars in 3012 bytes} [Mon Jun 21 16:06:05 2021] GET /result/2 => generated 7586 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 16/16] 172.17.0.1 () {62 vars in 3012 bytes} [Mon Jun 21 16:15:15 2021] GET /result/2 => generated 7586 bytes in 56 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 17/17] 172.17.0.1 () {62 vars in 3012 bytes} [Mon Jun 21 16:15:26 2021] GET /result/2 => generated 7586 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 18/18] 172.17.0.1 () {60 vars in 2935 bytes} [Mon Jun 21 16:15:34 2021] GET /result/1 => generated 7579 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 19/19] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:16:27 2021] GET /result/1 => generated 7579 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 20/20] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:16:35 2021] GET /result/1 => generated 7579 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 21/21] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:18:31 2021] GET /result/1 => generated 7579 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 22/22] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:19:12 2021] GET /result/1 => generated 7579 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 23/23] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:19:13 2021] GET /result/1 => generated 7579 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 24/24] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:23:12 2021] GET /result/1 => generated 7588 bytes in 23 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 25/25] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:23:13 2021] GET /result/1 => generated 7588 bytes in 102 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 26/26] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:23:14 2021] GET /result/1 => generated 7588 bytes in 85 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 27/27] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:23:15 2021] GET /result/1 => generated 7588 bytes in 15 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 28/28] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:23:16 2021] GET /result/1 => generated 7588 bytes in 75 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 29/29] 172.17.0.1 () {62 vars in 2964 bytes} [Mon Jun 21 16:23:21 2021] GET /result/1 => generated 7588 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Not Found: /favicon.ico
[pid: 2306|app: 0|req: 30/30] 172.17.0.1 () {60 vars in 2902 bytes} [Mon Jun 21 16:23:22 2021] GET /favicon.ico => generated 2987 bytes in 9 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 31/31] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:23:39 2021] GET /result/1 => generated 7588 bytes in 94 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 32/32] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:25:23 2021] GET /result/1 => generated 7588 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 33/33] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:26:48 2021] GET /result/1 => generated 7215 bytes in 45 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 34/34] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:26:50 2021] GET /result/1 => generated 7215 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 35/35] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:26:51 2021] GET /result/1 => generated 7215 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 36/36] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:27:03 2021] GET /result/1 => generated 7588 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 37/37] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 16:31:33 2021] GET /result/2 => generated 7586 bytes in 28 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 38/38] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 16:31:37 2021] GET /result/3 => generated 7552 bytes in 14 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Internal Server Error: /result/0
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 50, in result
    developer = Developer.objects.get(pk=developer_id)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
main.models.Developer.DoesNotExist: Developer matching query does not exist.
[pid: 2306|app: 0|req: 39/39] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 16:31:42 2021] GET /result/0 => generated 70244 bytes in 208 msecs (HTTP/1.1 500) 6 headers in 186 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 40/40] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 16:31:45 2021] GET /result/1 => generated 7579 bytes in 36 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 41/41] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:33:41 2021] GET /result/1 => generated 7601 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 42/42] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:40:19 2021] GET /result/1 => generated 7612 bytes in 92 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 43/43] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:40:21 2021] GET /result/1 => generated 7612 bytes in 70 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Internal Server Error: /result/0
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 50, in result
    developer = Developer.objects.get(pk=developer_id)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/db/models/query.py", line 437, in get
    self.model._meta.object_name
main.models.Developer.DoesNotExist: Developer matching query does not exist.
[pid: 2306|app: 0|req: 44/44] 172.17.0.1 () {58 vars in 2957 bytes} [Mon Jun 21 16:40:22 2021] GET /result/0 => generated 70584 bytes in 320 msecs (HTTP/1.1 500) 6 headers in 186 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 45/45] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:40:36 2021] GET /result/1 => generated 7603 bytes in 100 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 46/46] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:40:37 2021] GET /result/1 => generated 7603 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 47/47] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:40:38 2021] GET /result/1 => generated 7603 bytes in 10 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 48/48] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:40:39 2021] GET /result/1 => generated 7603 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 49/49] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:40:39 2021] GET /result/1 => generated 7603 bytes in 25 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 50/50] 172.17.0.1 () {60 vars in 2988 bytes} [Mon Jun 21 16:40:40 2021] GET /result/1 => generated 7603 bytes in 32 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 51/51] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:41:16 2021] GET /result/1 => generated 7612 bytes in 104 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 52/52] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:41:35 2021] GET /result/1 => generated 8434 bytes in 13 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 53/53] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:41:47 2021] GET /result/1 => generated 8410 bytes in 21 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 54/54] 172.17.0.1 () {60 vars in 2942 bytes} [Mon Jun 21 16:41:48 2021] GET /result/1 => generated 8410 bytes in 62 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 55/55] 172.17.0.1 () {58 vars in 2911 bytes} [Mon Jun 21 16:41:51 2021] GET /result/2 => generated 8246 bytes in 22 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 56/56] 172.17.0.1 () {58 vars in 2895 bytes} [Mon Jun 21 16:42:13 2021] GET / => generated 2473 bytes in 5 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 57/57] 172.17.0.1 () {42 vars in 603 bytes} [Mon Jun 21 16:42:25 2021] GET / => generated 2473 bytes in 6 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 58/58] 172.17.0.1 () {40 vars in 679 bytes} [Mon Jun 21 16:42:39 2021] GET / => generated 2473 bytes in 7 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 59/59] 172.17.0.1 () {42 vars in 741 bytes} [Mon Jun 21 16:42:44 2021] GET /form/ => generated 37977 bytes in 340 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 60/60] 172.17.0.1 () {50 vars in 1006 bytes} [Mon Jun 21 16:43:12 2021] POST /submit/ => generated 0 bytes in 36 msecs (HTTP/1.1 302) 6 headers in 188 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 61/61] 172.17.0.1 () {46 vars in 891 bytes} [Mon Jun 21 16:43:13 2021] GET /result/3 => generated 7866 bytes in 9 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 62/62] 172.17.0.1 () {60 vars in 2926 bytes} [Mon Jun 21 16:43:41 2021] GET / => generated 2473 bytes in 5 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Mon Jun 21 16:43:47 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /form/ (ip 172.17.0.1) !!!
Mon Jun 21 16:43:47 2021 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /form/ (172.17.0.1)
OSError: write error
[pid: 2306|app: 0|req: 63/63] 172.17.0.1 () {60 vars in 2964 bytes} [Mon Jun 21 16:43:47 2021] GET /form/ => generated 0 bytes in 266 msecs (HTTP/1.1 200) 7 headers in 0 bytes (0 switches on core 0)
[pid: 2306|app: 0|req: 64/64] 172.17.0.1 () {60 vars in 2964 bytes} [Mon Jun 21 16:43:47 2021] GET /form/ => generated 37977 bytes in 468 msecs (HTTP/1.1 200) 7 headers in 350 bytes (1 switches on core 0)
Internal Server Error: /submit/
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 32, in submit
    developer_id = int(request.POST[f'question-{n}'][0])
IndexError: string index out of range
[pid: 2306|app: 0|req: 65/65] 172.17.0.1 () {68 vars in 3171 bytes} [Mon Jun 21 16:44:08 2021] POST /submit/ => generated 63981 bytes in 305 msecs (HTTP/1.1 500) 6 headers in 186 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 66/66] 172.17.0.1 () {58 vars in 2907 bytes} [Mon Jun 21 16:44:18 2021] GET /submit => generated 0 bytes in 1 msecs (HTTP/1.1 301) 5 headers in 176 bytes (1 switches on core 0)
Internal Server Error: /submit/
Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)
KeyError: 'question-1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./main/views.py", line 32, in submit
    developer_id = int(request.POST[f'question-{n}'][0])
  File "/workspace/mbittest/venv/lib/python3.7/site-packages/django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
django.utils.datastructures.MultiValueDictKeyError: 'question-1'
[pid: 2306|app: 0|req: 67/67] 172.17.0.1 () {58 vars in 2909 bytes} [Mon Jun 21 16:44:18 2021] GET /submit/ => generated 69954 bytes in 205 msecs (HTTP/1.1 500) 6 headers in 186 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 68/68] 172.17.0.1 () {68 vars in 3171 bytes} [Mon Jun 21 16:44:53 2021] POST /submit/ => generated 0 bytes in 37 msecs (HTTP/1.1 302) 6 headers in 188 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 69/69] 172.17.0.1 () {62 vars in 3006 bytes} [Mon Jun 21 16:44:53 2021] GET /result/5 => generated 8022 bytes in 8 msecs (HTTP/1.1 200) 5 headers in 167 bytes (1 switches on core 0)
Not Found: /ㅁ으ㅑㅜ
[pid: 2306|app: 0|req: 70/70] 172.17.0.1 () {58 vars in 2943 bytes} [Mon Jun 21 16:45:54 2021] GET /%E3%85%81%EC%9C%BC%E3%85%91%E3%85%9C => generated 3014 bytes in 17 msecs (HTTP/1.1 404) 5 headers in 159 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 71/71] 172.17.0.1 () {58 vars in 2907 bytes} [Mon Jun 21 16:45:59 2021] GET /admin/ => generated 7581 bytes in 197 msecs (HTTP/1.1 200) 8 headers in 293 bytes (1 switches on core 0)
Mon Jun 21 16:46:04 2021 - SIGPIPE: writing to a closed pipe/socket/fd (probably the client disconnected) on request /admin/main/question/ (ip 172.17.0.1) !!!
Mon Jun 21 16:46:04 2021 - uwsgi_response_writev_headers_and_body_do(): Broken pipe [core/writer.c line 306] during GET /admin/main/question/ (172.17.0.1)
OSError: write error
[pid: 2306|app: 0|req: 72/72] 172.17.0.1 () {60 vars in 3000 bytes} [Mon Jun 21 16:46:04 2021] GET /admin/main/question/ => generated 0 bytes in 376 msecs (HTTP/1.1 200) 9 headers in 0 bytes (0 switches on core 0)
[pid: 2306|app: 0|req: 73/73] 172.17.0.1 () {60 vars in 3000 bytes} [Mon Jun 21 16:46:04 2021] GET /admin/main/question/ => generated 9474 bytes in 406 msecs (HTTP/1.1 200) 9 headers in 461 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 74/74] 172.17.0.1 () {56 vars in 2805 bytes} [Mon Jun 21 16:46:05 2021] GET /admin/jsi18n/ => generated 3195 bytes in 133 msecs (HTTP/1.1 200) 6 headers in 189 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 75/75] 172.17.0.1 () {60 vars in 3032 bytes} [Mon Jun 21 16:46:08 2021] GET /admin/main/question/1/change/ => generated 7091 bytes in 192 msecs (HTTP/1.1 200) 9 headers in 461 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 76/76] 172.17.0.1 () {56 vars in 2814 bytes} [Mon Jun 21 16:46:08 2021] GET /admin/jsi18n/ => generated 3195 bytes in 12 msecs (HTTP/1.1 200) 6 headers in 189 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 77/77] 172.17.0.1 () {60 vars in 3019 bytes} [Mon Jun 21 16:46:10 2021] GET /admin/main/choice/ => generated 20917 bytes in 891 msecs (HTTP/1.1 200) 9 headers in 462 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 78/78] 172.17.0.1 () {56 vars in 2803 bytes} [Mon Jun 21 16:46:11 2021] GET /admin/jsi18n/ => generated 3195 bytes in 13 msecs (HTTP/1.1 200) 6 headers in 189 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 79/79] 172.17.0.1 () {60 vars in 3026 bytes} [Mon Jun 21 16:46:15 2021] GET /admin/main/choice/6/change/ => generated 10516 bytes in 482 msecs (HTTP/1.1 200) 9 headers in 462 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 80/80] 172.17.0.1 () {56 vars in 2812 bytes} [Mon Jun 21 16:46:16 2021] GET /admin/jsi18n/ => generated 3195 bytes in 26 msecs (HTTP/1.1 200) 6 headers in 189 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 81/81] 172.17.0.1 () {60 vars in 3035 bytes} [Mon Jun 21 16:47:07 2021] GET /admin/main/choice/6/delete/ => generated 5685 bytes in 179 msecs (HTTP/1.1 200) 9 headers in 461 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 82/82] 172.17.0.1 () {58 vars in 3001 bytes} [Mon Jun 21 16:47:17 2021] GET /admin/main/choice/6/change/ => generated 10516 bytes in 302 msecs (HTTP/1.1 200) 9 headers in 462 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 83/83] 172.17.0.1 () {68 vars in 3233 bytes} [Mon Jun 21 16:48:08 2021] POST /admin/main/choice/6/change/ => generated 0 bytes in 96 msecs (HTTP/1.1 302) 10 headers in 683 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 84/84] 172.17.0.1 () {62 vars in 3362 bytes} [Mon Jun 21 16:48:08 2021] GET /admin/main/choice/ => generated 21188 bytes in 832 msecs (HTTP/1.1 200) 10 headers in 560 bytes (1 switches on core 0)
[pid: 2306|app: 0|req: 85/85] 172.17.0.1 () {56 vars in 2803 bytes} [Mon Jun 21 16:48:09 2021] GET /admin/jsi18n/ => generated 3195 bytes in 6 msecs (HTTP/1.1 200) 6 headers in 189 bytes (1 switches on core 0)
Gracefully killing worker 1 (pid: 2306)...
...gracefully killing workers...
worker 1 buried after 1 seconds
binary reloading uWSGI...
chdir() to /workspace/mbittest
closing all non-uwsgi socket fds > 2 (max_fd = 1024)...
found fd 3 mapped to socket 0 (/workspace/mbittest/tmp/MBIT.sock)
running /workspace/mbittest/venv/bin/uwsgi
[uWSGI] getting INI configuration from /workspace/mbittest/.config/uwsgi/uwsgi.ini
[uwsgi-static] added mapping for /static => /workspace/mbittest/staticfiles/
*** Starting uWSGI 2.0.19.1 (64bit) on [Mon Jun 21 16:48:37 2021] ***
compiled with version: 7.5.0 on 21 June 2021 11:21:56
os: Linux-4.4.0-1128-aws #142-Ubuntu SMP Fri Apr 16 12:42:33 UTC 2021
nodename: goorm
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 2
current working directory: /workspace/mbittest
detected binary path: /workspace/mbittest/venv/bin/uwsgi
chdir() to /workspace/mbittest/
your memory page size is 4096 bytes
detected max file descriptor number: 1024
building mime-types dictionary from file /etc/mime.types...554 entry found
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 inherited UNIX address /workspace/mbittest/tmp/MBIT.sock fd 3
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
Python version: 3.7.4 (default, Nov  4 2020, 10:17:35)  [GCC 7.4.0]
PEP 405 virtualenv detected: /workspace/mbittest/venv/
Set PythonHome to /workspace/mbittest/venv/
Python main interpreter initialized at 0x55d2e2cd4f80
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 145840 bytes (142 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 9 seconds on interpreter 0x55d2e2cd4f80 pid: 2302 (default app)
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
gracefully (RE)spawned uWSGI master process (pid: 2302)
spawned uWSGI worker 1 (pid: 5215, cores: 1)
subprocess 4938 exited with code 0
